### ISSUE TITLE
Add hands and face detection and pose?

### ISSUE THREAD

**Issue by ianni67** [stereolabs/zed-openpose#1]
Hello,
thank you for sharing all this great software. 
I'm experimenting with the ZED camera and openpose. I already tried the demo and played with it, making small changes and so. Now I'd like to track hands pose but can not understand what the correct pathway is. The corresponding example in openpose (openpose/examples/openpose/openpose.cpp) has a completely different structure with respect to zed-openpose and it calls a number of wrappers and so. Following the flow of that software is a nightmare.
Your readme states that it would not be hard to add hands and face pose trackingto zed-openpose. Would you, please, elaborate on that and provide more details?
Thank you very much for your help

**Comment by adujardin** [comment]
Hi
This code was developed a while ago and didn't use the abstracted wrapper for pose detection. You could try to skip the wrapper to have something closer to the existing code for the hand. 

It seems the hand extractor needs to be used in combination with the hand detector. The [hand detector](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/hand/handDetector.hpp) extracts patches of hand location and the [hand extractor](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/hand/handExtractorNet.hpp) the hand keypoints.

The face detection module seems to work similarly ([faceDetector](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/face/faceDetector.hpp), [faceExtractor](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/include/openpose/face/faceExtractorNet.hpp)).

You should be aware that the ZED depth map might lack details to estimates accurately the hand keypoints location outside the close range.
