### ISSUE TITLE
Any update plan for the latest OpenPose?

### ISSUE THREAD

**Issue by rathaROG** [stereolabs/zed-openpose#10]
Hi, I've just purchased two of ZED 2 and my main purpose is to try this zed-openpose, but this repo doesn't seem to work with the current master OpenPose. The current OpenPose was built successfully on Windows with CUDA 11.0. I tried to fix a few stuffs and also update some lines codes in the main.cpp, but no luck. I still can't make it work.  

![Screenshot (13)](https://user-images.githubusercontent.com/10178493/105038601-d2cd6080-5a5f-11eb-9eb8-6e571900066c.png)

**Comment by rathaROG** [comment]
Solved. I manually checked and added all the required include directories and import libs.

**Comment by benMOOVENCY** [comment]
> 
> 
> Solved. I manually checked and added all the required include directories and import libs.

Hello, could you please show which directories and import libs are missing, i have the same issue.
