### ISSUE TITLE
Commit to this repository. 

### ISSUE THREAD

**Issue by albertoperdomo2** [stereolabs/zed-openpose#11]
How can one commit to this repository? I have found some issues that I have locally fixed and I want to push the changes to this repo, but I am not allowed. 

Is this something that is being considered?

**Comment by adujardin** [comment]
You can't directly commit to our repository (pretty standard to avoid everybody submitting random changes), you need to fork the repo, make the change into a branch then submit a pull request, we'll then review it and potentially merge it if we think it needs to be, see the GitHub doc for more details: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests
