### ISSUE TITLE
[Ubuntu 18.04] make Error 1 and Error 2

### ISSUE THREAD

**Issue by giopri13** [stereolabs/zed-openpose#13]
Hello everyone, I'm trying to build the sample on Ubuntu 18.04.

I'm using an older version of Ubuntu because I downgraded to Openpose 1.5.1 to solve the problem described in the following [pull request](https://github.com/stereolabs/zed-openpose/pull/12). Unfortunately, while the scaleAndSizeExtractor issue is no more, I'm now stuck here with this [output](https://pastebin.com/a6j8NwD4).

I installed Opencv with apt-get install libopencv-dev, as specified on the prerequisites section of the Openpose Installation guide. It seems like I have Opencv 3.2
Should I downgrade to a specific Opencv version? If yes, could you please suggest me which one works best natively?

Thank you for your attention

**Comment by albertoperdomo2** [comment]
Hey. That PR was created to patch OpenPose v1.7.0, and make it work with its ZED integration. 

As far as I understand from your question, you are using a previous version that has nothing to do with the purpose of this PR.

**Comment by giopri13** [comment]
> Hey. That PR was created to patch OpenPose v1.7.0, and make it work with its ZED integration.
> 
> As far as I understand from your question, you are using a previous version that has nothing to do with the purpose of this PR.

My wording wasn't really spot on. I meant to say that I downgraded to 1.5.1 to avoid the scaleAndSizeExtractor issue described and solved in that PR. I mentioned it just because it was already known, and unfortunately the PR was published after I had installed 1.7.0, had the same issue, and decided to go down the downgrade route.

My issue is that, with this older version, I'm having other compiling problems, not described anywhere as far as I could understand. The errors are in the pastebin link in the original post.

**Comment by albertoperdomo2** [comment]
As far as I know, Zed-OpenPose integration was developed using OpenPose v1.6.0, so my guess is that (without being able to check the code atm) your installed version of OpenPose is too old for this integration in particular. I would recommend using v1.6.0 or v1.7.0 with that workaround showed in my PR.

**Comment by giopri13** [comment]
> As far as I know, Zed-OpenPose integration was developed using OpenPose v1.6.0, so my guess is that (without being able to check the code atm) your installed version of OpenPose is too old for this integration in particular. I would recommend using v1.6.0 or v1.7.0 with that workaround showed in my PR.

Thank you for your reply. I'll try with Openpose 1.6.0 and, if it doesn't work, I'll be back on Ubuntu 20.04 with Openpose 1.7.0

**Comment by giopri13** [comment]
Thank you! I finally made it work!
