### ISSUE TITLE
GPU available

### ISSUE THREAD

**Issue by alexismurari** [stereolabs/zed-openpose#16]
Does this program auto-detects and use all GPUs available?

If not how to enable the use of 2 GPUs?

Thank you!

**Comment by adujardin** [comment]
It's using only 1 GPU by default.

You could assign one GPU to the ZED SDK and another one to OpenPose.

1. For the ZED SDK add an init parameter such as `initParameters.sdk_gpu_id=0` [here](https://github.com/stereolabs/zed-openpose/blob/c3ba895db73240340cf6eab8c8c6ced87505f947/src/main.cpp#L145)

2. For Openpose change the `FLAGS_num_gpu_start` parameter [here](https://github.com/stereolabs/zed-openpose/blob/c3ba895db73240340cf6eab8c8c6ced87505f947/src/main.cpp#L209)

**Comment by alexismurari** [comment]
Thank you for you quick reply.

This works however I would require to use the most out of both of my GPUs. Both of my GPUs have 8GB of VRAM, this solution only allows me to use 9GB/16.

Is there any other alternative I could use? 

Thank you for your help and time.

**Comment by obraun-sl** [comment]
Hi,
You can use ZED Explorer without a NVIDIA GPU. You just won't have access to all the compression mode (H264/H265 are based on NVIDIA encoding, but LOSSLESS is available even without NVIDIA GPU)

**Comment by alexismurari** [comment]
Hello,
I am not sure to understand is this for the zed-openpose program?

**Comment by obraun-sl** [comment]
Sorry - I answered on the wrong issue
