### ISSUE TITLE
zed_openpose.exe can't get build, error: empty frames

### ISSUE THREAD

**Issue by FelixMut** [stereolabs/zed-openpose#2]
Hello,
we would like to test the camera with this very usefull software in our laboratory. So we tried to install it on a pc with an Intel i7-8700K, 16 GB RAM and Nvidia's Quadro P2000 (5 GB VRAM)
but we had some issues while doing it. Now we think we have installed at least openpose correctly on windows 10 1909 but when we have integrated the zed-openpose folder at C:\Users\ZED Camera\Documents\openpose-master\examples\user_code\zed-openpose and run Cmake on this folder it can't find some directories. If we try to run Cmake after this integration at C:\Users\ZED Camera\Documents\openpose-master (set as source Code directory) we can configure and generate it with Cmake but the zed_openpose.exe doesn't get build. So we can only run the C:\Users\ZED Camera\Documents\openpose-master\build\OpenPose.sln on Visual Studio 2017

![Cmake_build_openpose-master_genereated](https://user-images.githubusercontent.com/58261918/69730993-583dd500-1129-11ea-97a5-be2a9c325542.PNG)

but when we try to run the .sln file an empty OpenPose 1.5.1 window appears and in the console we see these error messages:

_"[ WARN:1] global C:\build\master_winpack-build-win64-vc14\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638
Camera frame empty (it has occurred for the last 2 consecutive frames)."_
_"[ WARN:1] global C:\build\master_winpack-build-win64-vc14\opencv\modules\videoio\src\cap_msmf.cpp (1159) CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -2147483638
Camera frame empty (it has occurred for the last 3 consecutive frames)."_

![Running_OpenPose-sln](https://user-images.githubusercontent.com/58261918/69730914-3e03f700-1129-11ea-8335-ce741e3824a7.PNG)

this is counting upwards as long as we run the OpenPose.sln and it doesn't matter if we run it with the ZED Stereo Camera or a Logitech USB webcam. The only difference between these two cameras is that the LED at the webcam gets turned on while running the OpenPose.sln but not at the ZED Stereo Camera (both Cameras were checked one by one).

 
Here are the steps we have done so far:

1. uninstalled Nvidia drivers and deleted the Nvidia folders C:\Program Files (x86)\NVIDIA Corporation and C:\Program Files\NVIDIA GPU Computing Toolkit and in this director again the NVIDIA Corporation
2. installed Visual Studio 2017
3. installed ZED SDK 2.8.3 and in this process we installed CUDA 10.0 (default Location: C:\Program Files (x86)\ZED SDK) -> ZED SDK is running fine with the ZED Stereo Camera
4. installed cudnn v7.6.5 (November 5th, 2019), for CUDA 10.0 (copied the files in the cuda folders)
5. cloned openpose 1.5.1 via GitHub Desktop application
6. downloaded the Caffe, OpenCV, and Caffe prerequisites (5. at https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/prerequisites.md) 

- CUDA Caffe (Default)
- CPU Caffe
- OpenCL Caffe
- Caffe dependencies
- OpenCV 4.1.1
- Freeglut via batch file
all unziped at C:\Users\ZED Camera\Documents\openpose-master\3rdparty\Windows

7. installed Cmake 3.16.0-rc3
8. build OpenPose with Cmake and got the OpenPose.sln in the build folder
9. cloned zed-openpose (https://github.com/stereolabs/zed-openpose) in C:\Users\ZED Camera\Documents\openpose-master\examples\user_code\zed-openpose and ran Cmake again. _(How I said on the openpose-master folder because the zed-openpose folder alone didn't work because GLEW_DIR and CUDA_SDK_ROOT_DIR - wer not found.)_

![Cmake_build_zed-openpose_error](https://user-images.githubusercontent.com/58261918/69730891-2f1d4480-1129-11ea-9ee8-d3b49bd546e7.PNG)

 We got no errors but neither the zed_openpose.exe.

We are not sure if we did the last step with the zed-openpose correctly, because we don't know if the "user_code" directory is the place where zed-openpose should be. Also we only can guess how to build zed-openpose correctly with Cmake because the commands of the ReadMe are not working in Windows 10's cmd.

That's why we also tried to install it on Linux Ubuntu 18.04. When we try to build zed-openpose on Ubuntu with Cmake it can't find the glew directory and we can't find it manually.

We hope you can help us how to install these software packages correctly.

**Comment by adujardin** [comment]
Hi,
I just pushed a fix that should solve the `glew` issue on Linux.

On Windows, you should first make sure OpenPose without the ZED is working properly, like compiling the example and running them on a webcam, then compiling zed-openpose.
Although I recommend using Ubuntu for this, if that is an option, it will be easier to set up the environment.
