### ISSUE TITLE
CMake Error at CMakeLists.txt:18

### ISSUE THREAD

**Issue by kuroneko306** [stereolabs/zed-openpose#8]
Hello,

I am trying to build the sample on Windows. However, I got the error message when executing cmake.

CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindOpenPose.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenPose",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenPose" with any
  of the following names:

    OpenPoseConfig.cmake
    openpose-config.cmake

  Add the installation prefix of "OpenPose" to CMAKE_PREFIX_PATH or set
  "OpenPose_DIR" to a directory containing one of the above files.  If
  "OpenPose" provides a separate development package or SDK, be sure it has
  been installed.

Where can I find the missing files?

Thank you very much

**Comment by bl0up** [comment]
Hello, 

I'm facing the same problem, did you manage to solve it? 

Thank you very much

**Comment by obraun-sl** [comment]
Hi,
Did you clone and build the openpose repository as mentionned in the installation guide ?
https://github.com/stereolabs/zed-openpose#installation

**Comment by bl0up** [comment]
I did, the openpose demo is running but I can't configure the zed-openpose project. OpenPoseConfig.cmake seems to be missing.

**Comment by obraun-sl** [comment]
The OpenPoseConifg.cmake file is installed by the "sudo make install" done after building openpose 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/cmake/OpenPoseConfig.cmake.in

Can you check that it exists in the folder of the open pose of the installation?

**Comment by bl0up** [comment]
It exists in the folder, but I'm using windows, unfortunately.

**Comment by thrivinb** [comment]
> It exists in the folder, but I'm using windows, unfortunately.

Hi @adujardin @kuroneko306 @obraun-sl  @bl0up , I'm also using Windows and experiencing the same error, can I check if you managed to resolve it on your end ?

**Comment by alihan-ozturk** [comment]
I'm facing the same problem
